# Introduction to Numpy

The **NumPy** library provides mathematical functions such as matrix algebra and and statistical analysis, and allows us to work with the Numpy ndarray type. The **ndarray** type is an ordered, indexed, and mutable. They are also commonly homogeneous. Numpy was written with C and will perform processing much faster than a Python list. It also stores values contiguously in memory. 

Consider (image source: https://www.geeksforgeeks.org/python/python-lists-vs-numpy-arrays/): 

<img src="https://media.geeksforgeeks.org/wp-content/uploads/20230824164516/1.png" alt="How Python Lists are stored" width="50%" height="50%"/>
Versus:
<img src="https://media.geeksforgeeks.org/wp-content/uploads/20230824164544/2.png" alt="How NumPy Arrays are stored" width="50%" height="50%"/>

We use the array() function to create an **ndarray** (n-dimensional array). This requires us to import NumPy library first. 

Great beginner's guide can be found at [numpy website](https://numpy.org/doc/stable/user/absolute_beginners.html).

### Getting Started

Arrays can be zero-dimensional, one-dimensional, or many dimensions. 

In [27]:
import numpy as np

scalar = np.array(3) #scalar
print(scalar)

oneD = np.array([0,1]) #1d array - like a list
print(oneD)

twoD = np.array([[1,2], [3,4]])  #2d array
print(twoD)

3
[0 1]
[[1 2]
 [3 4]]


Array **shape** is the tuple of level sizes. Each level should have the same size (number of elements), so the shape should be a rectangle or square.

Array **size** is the number of elements total.

There are some [attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#id1) that we access to obtain information about the array. 

In [4]:
my_array = np.array([[1,2], [3,4], [5, 6]])

print(my_array.shape)
print(my_array.size)
print(my_array.dtype)

(3, 2)
6
int32


In [6]:
# Cannot do
my_array = np.array([[1,2], [3,4], [5]])
# Does not like ragged lengths

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

You can index and slice NumPy arrays just like you do Python lists. However, when working with 2D arrays we use a comma between row and column values (e.g. [,]) instead of using the [ ][ ] syntax. 

In [9]:
# We can access elements using row & column index values
print(my_array)
print("first item is", my_array[0,0])  # [row, col]
print("last item is", my_array[2,1])

print("first row is", my_array[0])
print("last row is", my_array[1])

[[1 2]
 [3 4]
 [5 6]]
first item is 1
last item is 6
first row is [1 2]
last row is [3 4]


In [11]:
my_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

# we want the first item in each row
print(my_array[0:3,0]) # [row, col]

# we want the last two items of each row
print(my_array[0:3,1:3])

[1 4 7]
[[2 3]
 [5 6]
 [8 9]]


**Question 1**

How do we get the first 2 items in the first row?

How do we get the last 2 items in the last two rows?

In [28]:
print(my_array)
print(my_array[0, 0:2])
print(my_array[1:3, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2]
[[5 6]
 [8 9]]


When you use a slice or reference an element by the index, you are returned a **view**.  

In [30]:
# what happens when you manipulate a slice?
# first_col is a slice of the original array
# it contains the first value in each row
print("Original Array\n", my_array)
first_col = my_array[0:3,0]  # this gives you a view!
print("First Column(before)\n",first_col)

# let's manipulate this 
first_col[0:3] = first_col[0:3] + 1  # add one to each value in this slice
# first_col[0:3] + 1  # not just this -- won't update original
# first_col[0:3] += 1  # but can do this -- will update original

print("First Column(after)\n",first_col)

# Did this impact the original array?
print("Original Array\n", my_array) # take note here!!!!!!!!!!!!!

Original Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First Column(before)
 [1 4 7]
First Column(after)
 [2 5 8]
Original Array
 [[2 2 3]
 [5 5 6]
 [8 8 9]]


Major difference is that slicing with arrays returns a **view**. Views are objects that refer to the data in the original array and therefore can be used to manipulate the original data. Views have the same memory address as the original array. 

**Question 2**

Update first row of the ndarray array (my_array). Subtract one from each value in the first row.





In [38]:
print(my_array[0])
my_array[0] = my_array[0] - 1
print(my_array)

[2 2 3]
[[1 1 2]
 [5 5 6]
 [8 8 9]]


To obtain a copy of the data, you need a function. More on functions below.

### Functions and Methods

There are several ndarray functions and methods we'll use to work with ndarrays. See documentation for reference:

* [Methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#methods) 
* [Functions](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

Many NumPy package functions have equivalent ndarray methods. Ex: np.sort(array) is equivalent to array_name.sort(). 

Some examples include:

* delete()
* fill()
* insert()
* zeros()
* ones()
* sort()
* mean()

Take note of whether you are using a numpy function vs an array method. If you are not directly manipulating the object, you'll need to set the instance equal to the call to retain any changes intended to the original object. 

In [40]:
# create array with 5 rows and 4 columns - store all zeros
new_array = np.zeros((5,4), dtype="int")
# note there is a similar function called ones()

new_array.fill(1)  # ndarray method to fill entire array with 1s
 
print(new_array)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [42]:
# add row at end and fill it with 2s -- numpy function
# axis 0 means row
new_array = np.insert(new_array, 5, 2, axis=0)
print(new_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [2 2 2 2]]


In [44]:
# add column at end and fill it with 3s -- numpy function
# axis 1 means column
new_array = np.insert(new_array, 4, 3, axis=1)
print(new_array)


[[1 1 1 1 3]
 [1 1 1 1 3]
 [1 1 1 1 3]
 [1 1 1 1 3]
 [1 1 1 1 3]
 [2 2 2 2 3]]


Take note above and consider when a numpy function vs method call is found.

Here are a few other function examples:

In [52]:
# other numpy functions
numbers_array = np.zeros(6).reshape(2,3)
print(numbers_array)

# get array by using a range function and then reshape to n dimensions
numbers_array = np.arange(6).reshape(3, 2)
print(numbers_array)

# delete first row
numbers_array = np.delete(numbers_array, 0, axis=0)
print(numbers_array)

# delete first column
numbers_array = np.delete(numbers_array, 0, axis=1)
print(numbers_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 1]
 [2 3]
 [4 5]]
[[2 3]
 [4 5]]
[[3]
 [5]]


In [58]:
# more numpy functions
numbers_array = np.array([[3, 2], [5, 6], [1, 2], [5, 1]])

#print(np.sort(numbers_array, axis=0)) # orders by col
print(np.sort(numbers_array, axis=1)) # puts rows in order

print(numbers_array) # note the original array is unchanged

[[2 3]
 [5 6]
 [1 2]
 [1 5]]
[[3 2]
 [5 6]
 [1 2]
 [5 1]]


**Question 3**

Refer to documentation. How can you sort all the values (e.g. as a flattened array)? See https://numpy.org/doc/stable/reference/generated/numpy.sort.html.

There is a large list of mathematical functions than can be called. https://numpy.org/doc/stable/reference/routines.math.html What they return can vary depending on how you use them.

In [60]:
# array functions
numbers_array = np.array([[3, 2], [5, 6], [0, 2], [5, 1]])
numbers_array.mean() # returns just one number

3.0

In [62]:
numbers_array.mean(axis=0) # returns array of means - column means
# more on these in a bit

array([3.25, 2.75])

In [64]:
# other methods

# determine which indices do not contain zero
numbers_array.nonzero()

(array([0, 0, 1, 1, 2, 3, 3], dtype=int64),
 array([0, 1, 0, 1, 1, 0, 1], dtype=int64))

In [66]:
# soring in place
numbers_array.sort(axis=1)
numbers_array

array([[2, 3],
       [5, 6],
       [0, 2],
       [1, 5]])

In [68]:
numbers_array.fill(3)
numbers_array

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

We can reshape and flatten our arrays. You often need to consider how to manipulate the data: row-major order (C) or column-major order (F). 

In [70]:
play_array = np.array([[3, 2], [5, 6], [0, 2], [5, 1]])
np.reshape(play_array, (8,1))
#np.reshape(play_array, (8,1), order='C')
#np.reshape(play_array, (8,1), order='F')

array([[3],
       [2],
       [5],
       [6],
       [0],
       [2],
       [5],
       [1]])

In [ ]:
play_array = np.array([[3, 2], [5, 6], [0, 2], [5, 1]])
play_array.ravel() # return a 1d array

**Question 4**

1. Create an array filled with zeros as ints. It should have 10 rows and 2 columns.
2. Create an 1d array containing numbers 1 through 10. 
3. Create an array containing even numbers between 0 and 19 and reshape to 5 rows 2 columns.

In [36]:
np.zeros(20, dtype=np.int_).reshape(10, 2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [38]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# Create an array containing even numbers between 0 and 19 and reshape to 5 rows 2 columns
np.arange(0, 19, 2).reshape(5, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

### Math operators and functions

We can use our typical operators (e.g. +, -, *, /, and %). They are applied to element pairs and returns an array. One of the nice aspects of numpy is the ability to do **element-wise** operations. Element-wise operations allow us to perform an operation on each element in the array. 

In [52]:
one = np.arange(6).reshape(3, 2)
two = np.arange(6).reshape(3, 2)

print(one)
print(two)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [48]:
#one = one + 3 # performing element-wise addition

In [50]:
one

array([[3, 4],
       [5, 6],
       [7, 8]])

In [56]:
# add corresponding array element values to each other
one + two
np.add(one, two) # same as above

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
one * two
np.multiply(one, two) # same as above

We can also compare arrays using comparison operators.  This will return an array with true and false values for each compared elements.

In [60]:
print(one)
print(two)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [62]:
one > two
# one == two

array([[False, False],
       [False, False],
       [False, False]])

We can use functions like min(), max(), median(), and var(). These will work on the entire array or slice. What they return is dependent on what you give them. For example, if you define an axis value, you'll typically get an array result instead of one value.

In [64]:
np.sqrt(one) # square root of array of elements
one

array([[0, 1],
       [2, 3],
       [4, 5]])

In [66]:
np.median(one) # median of array elements
np.median(one, axis=0) # median for each column

array([2., 3.])

In [68]:
# note that this can also be done on part of the array
print(one[0:2])
np.mean(one[0:2])

[[0 1]
 [2 3]]


1.5

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])
np.dot(a, b) # dot product of a rows with b columns
np.

**Question 5**

Create a 2D array A with shape (3, 3) filled with random integers between 1 and 9. Create another 2D array B with the same shape, filled with integers from 1 to 3. Perform element-wise multiplication of A and B.

Hint: 
rng = np.random.default_rng()

In [81]:
A = np.arange(1,10).reshape(3,3)
rng = np.random.default_rng()
B = rng.integers(low=1, high=4, size=(3,3))
C = A * B
print(A)
print(B)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [1 1 2]
 [3 2 3]]
[[ 3  6  9]
 [ 4  5 12]
 [21 16 27]]


### Note about ndarrays and pointers

Assigning an existing NumPy array to a new variable does not create a copy of the array but instead creates a pointer to the original array. If we want a copy of an ndarray that is not connected to the original source, we need to use the copy() function instead.

In [70]:
original = np.ones(7) # creates array filled with 1s
new = original # create copy?
original += 5 # modify original
print(new) # see that copy has been updated

[6. 6. 6. 6. 6. 6. 6.]


In [12]:
original_2 = np.ones(7) # creates array filled with 1s
new = np.copy(original_2) # create copy!
original += 5 # modify original
print(new) # see that copy has NOT been updated

[1. 1. 1. 1. 1. 1. 1.]


In [72]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])